const express = require('express');
const router = express.Router();
const gradeController = require('../controller/gradei.controller');
const user = require('../middleware/passport');
const passport = require('passport');
const { uploadFile } = require('../middleware/upload');
router.post('/create',passport.authenticate('jwt', {session: false}),user.requireUser, uploadFile.single('file'), gradeController.create);
router.patch('/updateOne/:id',passport.authenticate('jwt', {session: false}), user.requireTk, gradeController.updateOne);
router.get('/getOne/:id', gradeController.getOne);
router.get('/getAll',passport.authenticate('jwt', {session: false}), user.requireTk, gradeController.getAll);
router.delete('/deleteOne/:id',gradeController.deleteOne);
module.exports = router;